version: '3'

services:
  postgres:
    image: postgres:16
    container_name: viva-eularia-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: viva_eularia
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
